---
version: "3"
services:
  plex:
    image: lsioarmhf/plex
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/usb/movies:/data/movies
      - /mnt/usb/tvshows:/data/tvshows
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
