---
version: "3"
services:
  letsencrypt:
    image: linuxserver/letsencrypt:latest
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/appdata/letsencrypt:/config
    restart:
      always
    depends_on:
      - plex
      - tautulli
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - SUBDOMAINS=pi,plex,nextcloud,tautulli,portainer,photos
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=2048
      - VALIDATION=http
      - TZ=America/Chicago
    env_file:
      - general.env
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports:
      - 32400:32400
    volumes:
      - /mnt/appdata/plex:/config
      - /mnt/plex/movies:/data/movies
      - /mnt/plex/tvshows:/data/tvshows
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    ports:
      - 8181:8181
    depends_on:
      - plex
    volumes:
      - /mnt/appdata/tautulli:/config
      - /mnt/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  postgres:
    image: postgres:11.7
    container_name: postgres
    volumes:
      - /mnt/postgres:/var/lib/postgresql/data
    restart: always
    user: 1000:1000
    env_file:
      - db.env
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    ports:
      - 444:443
    volumes:
      - /mnt/appdata/nextcloud:/config
      - /mnt/nextcloud:/data
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  portainer:
    image: portainer/portainer:linux-arm-1.23.0
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/appdata/portainer:/data
    restart: always
  lychee:
    image: linuxserver/lychee:v3.2.16-ls61
    container_name: lychee
    volumes:
      - /mnt/appdata/lychee:/config
      - /mnt/pictures:/pictures
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    expose:
      - 80
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb:110.4.12mariabionic-ls60
    container_name: mariadb
    volumes:
      - /mnt/appdata/mariadb:/config
    ports:
      - 3306:3306
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    env_file:
      - mariadb.env
    restart: unless-stopped


