---
version: "3"
services:
  letsencrypt:
    image: lsioarmhf/letsencrypt
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt:/config
    restart:
      always
    depends_on:
      - plex
      - tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - EMAIL=austin.s.mcconnell@gmail.com
      - URL=austinmcconnell.me
      - SUBDOMAINS=pi,nextcloud
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=2048
      - VALIDATION=http
      - TZ=America/Chicago
  plex:
    image: lsioarmhf/plex
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/usb/movies:/data/movies
      - /mnt/usb/tvshows:/data/tvshows
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
  tautulli:
    image: lsioarmhf/tautulli
    container_name: tautulli
    ports:
      - 8181:8181
    depends_on:
      - plex
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  postgres:
    image: postgres:10.4
    container_name: postgres
    volumes:
      - /opt/appdata/postgres:/var/lib/postgresql
    restart: always
    env_file:
      - db.env
  nextcloud:
    image: lsioarmhf/nextcloud
    container_name: nextcloud
    ports:
      - 444:443
    volumes:
      - /opt/appdata/nextcloud:/config
      - /mnt/usb2:/data
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
