---
version: "3"
services:
  letsencrypt:
    image: lsioarmhf/letsencrypt:210
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt:/config
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.data]
    restart:
      always
    depends_on:
      - plex
      - tautulli
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - SUBDOMAINS=pi,plex,nextcloud,tautulli,homeassistant,portainer
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=2048
      - VALIDATION=http
      - TZ=America/Chicago
    env_file:
      - general.env
  plex:
    image: lsioarmhf/plex:136
    container_name: plex
    ports:
      - 32400:32400
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/plex/movies:/data/movies
      - /mnt/plex/tvshows:/data/tvshows
      - /mnt/plex/transcribe:/transcribe
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.data]
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
  tautulli:
    image: lsioarmhf/tautulli:134
    container_name: tautulli
    ports:
      - 8181:8181
    depends_on:
      - plex
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.data]
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  postgres:
    image: postgres:10.4
    container_name: postgres
    volumes:
      - /mnt/postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.data]
    restart: always
    user: 1000:1000
    env_file:
      - db.env
  nextcloud:
    image: lsioarmhf/nextcloud:119
    container_name: nextcloud
    ports:
      - 444:443
    volumes:
      - /opt/appdata/nextcloud:/config
      - /mnt/nextcloud:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.data]
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  home-assistant:
    image: homeassistant/armhf-homeassistant:0.84.6
    container_name: homeassistant
    ports:
      - 8123:8123
    volumes:
      - /opt/appdata/home-assistant:/config
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.data]
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  portainer:
    image: portainer/portainer:linux-arm-1.20.0
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.data]
    restart: always
