---
version: "3"
services:
  plex:
    image: lsioarmhf/plex
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/usb/movies:/data/movies
      - /mnt/usb/tvshows:/data/tvshows
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
  tautulli:
    image: lsioarmhf/tautulli
    container_name: tautulli
    depends_on:
      - plex
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
