---
version: "3"
services:
  letsencrypt:
    image: lsioarmhf/letsencrypt
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt:/config
    restart:
      always
    depends_on:
      - plex
      - tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - SUBDOMAINS=pi,nextcloud,plex,automation
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=2048
      - VALIDATION=http
      - TZ=America/Chicago
    env_file:
      - general.env
  plex:
    image: lsioarmhf/plex
    container_name: plex
    ports:
      - 32400:32400
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/plex/movies:/data/movies
      - /mnt/plex/tvshows:/data/tvshows
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
  tautulli:
    image: lsioarmhf/tautulli
    container_name: tautulli
    ports:
      - 8181:8181
    depends_on:
      - plex
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  postgres:
    image: postgres:10.4
    container_name: postgres
    volumes:
      - /opt/appdata/postgres:/var/lib/postgresql
    restart: always
    env_file:
      - db.env
  nextcloud:
    image: lsioarmhf/nextcloud
    container_name: nextcloud
    ports:
      - 444:443
    volumes:
      - /opt/appdata/nextcloud:/config
      - /mnt/nextcloud:/data
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
  home-assistant:
    container_name: home-assistant
    image: homeassistant/armhf-homeassistant
    ports:
      - 8123:8123
    volumes:
      - /opt/appdata/home-assistant:/config
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
